### ISSUE TITLE
Add option to remove trailing spaces on manual save?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [thaerkh/vim-workspace#14]
Hello! First off, I just gotta say that your plugin is a Godsend! It works all the time, every time, and makes changing work environments a breeze! So thank you! *fist bump*

Could there be an option to remove trailing spaces when the file is saved manually? I run guard for my tests so having vim-workspace regularly save the files I'm working on causes any associated tests to run when I'm not quite ready for it. By using a manual save, I can ensure that all of my additions and modifications are ready before guard kicks off my tests in the background.

Thanks again! 
All the best,
Blake

**Comment by workgena** [comment]
@Blake-LeBlanc just add this line to `~/.vimrc`

```vim
autocmd BufWritePre * :%s/\s\+$//e " Trim trailing spaces on Save
```

**Comment by Blake-LeBlanc** [comment]
Thank you @workgena !
