### ISSUE TITLE
Plugin causes cedit mode to misbehave, some invalid call in Command mode

### ISSUE THREAD

**Issue by simlei** [thaerkh/vim-workspace#16]
Rather significant misdemeanor of the plugin by switching down and on again one-by-one all of my installed plugins. Therefore, most probably it's vim-workspace, but this may not be 100% sure.

cedit command mode is by default invoked with ``<C-f>`` from the ``:`` command line

__Reproduction:__
- Enter Ex-command entering mode by typing ``:``
- Enter cedit Mode by typing ``<C-f>``
- in there, inter insert mode by typing ``i``
- leave insert mode by typing ``<Esc``

This will give you straight in the command entering mode the following error: 
```
Error detected while processing InsertLeave Auto commands for "*":                                           
E11: Invalid in command-line window; <CR> executes, CTRL-C quits: pclose|endif
```
Other stuff with changing modes misbehaves, too.
Which is kind of cryptic and hard to track down. vim-style command edit mode is kind of an important feature so I think this is not a small issue.

FWIW, my Vim-workspace-related variables:
```
nnoremap <leader><F10> :ToggleWorkspace<CR>
let g:workspace_autosave_untrailspaces = 0
let g:workspace_autosave = 0
let g:workspace_persist_undo_history = 0
```

As I have also suffered already from vim-workspace trying to reopen my undotree window (unsuccessfully), I think the blac/whitelist scheme according to which windows are handled could benefit from an update. I really like the plugin though, and it's a shame that I'll have to deactive it for the time being :/ cedit mode is kinda important for me. Wish I could help, but thats beyind my skills, I don't know VimL...

If you know a workaround for the meantime, in case you confirm the issue lies with the plugin, please let me know :) thank you!

**Comment by eyalk5** [comment]
I experienced the same issue in Oni
