### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by saiqulhaq** [thaerkh/vim-workspace#2]
I am using Mac, Neovim v0.2.0-1470-g6755262 and Ruby 2.3.0

This problem raised when neovim says there is duplicate buffer on /../../Session.vim when starting it up

The High CPU is caused by fsevent_watch that monitoring current nvim working directory
I found two fsevent_watch process using command ```ps aux | grep ruby``` every I activate vim-workspace plugin
So I have installed vim-workspace plugin twice to make sure that the high CPU usage is not caused by other plugin

**Comment by thaerkh** [comment]
Hi Saiqul,

Sorry I don't have a Mac to test fsevent_watch 's behaviour.

It sounds like the issue has to do with those watchers reacting to this plugin auto-saving your files and current session. If you set `let g:workspace_autosave = 0`, does it reduce fsevent_watch CPU usage?

To note, with the option above, the plugin would still auto save your session but only when you exit Vim, and it won't update it as you add more files to your session. Therefore, In the event of Vim crashing, you may lose your current session state.

Thaer

**Comment by saiqulhaq** [comment]
Adding ```let g:workspace_autosave = 0``` seems solved my issue
Thanks @thaerkh 

I'm new fan of your plugin
