### ISSUE TITLE
no matching autocommands

### ISSUE THREAD

**Issue by craigjmidwinter** [thaerkh/vim-workspace#3]
I keep getting "no matching autocommands" in workspaces. I'm not sure what is causing this, but my session doesn't seem to get saved, though the autosave feature seems to be working

**Comment by craigjmidwinter** [comment]
Actually, I'm also seeing the cursor moving when this message comes up (which is very frequent)

**Comment by santiagohecar** [comment]
I have had the same problem, after disable autosave this seem not happen anymore

**Comment by thaerkh** [comment]
@wardcraigj @gohcar what OS and version of Vim are you using?

**Comment by thaerkh** [comment]
I just added a commit that makes the autosave autocommands silent which should address your issues above.
I speculate you're using a version of vim that doesn't have the autocommands being triggered (the autocommands are not necessary for autosave to work, but helps in playing nicely with 3rd party plugin features that need to be triggered by a file save).

Hope that helps!

**Comment by santiagohecar** [comment]
Works well for me now, with vim 8.0.627 on ubuntu 14.04, thanks
