### ISSUE TITLE
"Unknown option: swapsync"

### ISSUE THREAD

**Issue by superDuperCyberTechno** [thaerkh/vim-workspace#7]
I am using Neovim on Ubuntu 16.04. Whenever I toggle a workspace (ToggleWorkspace), an error message saying "Unknown option: swapsync" comes up.

It still autosaves just fine, though.

**Comment by backdround** [comment]
I am using Neovim with Plug on Arch and have this error too. fortunately all features is working.

**Comment by thaerkh** [comment]
I just pushed a commit that fixes this issue - thanks for pointing this out!
